README.md

Deletes unnecessary text from README.

Delete test commit text from README

---

backend/.gitignore
backend/middleware.js
backend/package-lock.json
frontend/package-lock.json
frontend/src/components/common/MenuItemLists.js
frontend/src/components/common/NavigationBar.js
frontend/src/components/common/NavigationMenu.js

Added subtitles `Student`, `Instructor` and `Admin` and places correct navigationbar items under these subtitles 
resolves: Menussa näkyvät valinnat on jäsennelty alaotsikoiden (admin, ohjaaja, opiskelija) alle #41

Add subtitles for navigationbar menuitems

---

frontend/src/components/common/MenuItemLists.js
frontend/src/components/common/NavigationBar.js

resolves: #44 
Added new links to navigation menu:
- Reviews
- Current registrations
- Registration details
- Participants
- Registration Questions
- Customer Review Questions
- Peer Review Questions

Add new navigation links under admin-user

---

backend/controllers/sprints.js
backend/models/sprint.js
frontend/src/components/SprintsPage/SprintsDashboard.js
frontend/src/components/common/MenuItemLists.js

add sprint management page and backend/db logics

---

frontend/src/reducers/store.js

Co-authored-by: miahro mikko.ahro@gmail.com
Co-authored-by: RedFoxFinn development.redfox@gmail.com

Fix redux store initialization

---

frontend/src/components/SprintsPage/SprintsDashboard.css
frontend/src/components/SprintsPage/SprintsDashboard.js

Use similar styles as in Time Logs page

Add Sprint Dashboard styles

---

frontend/package.json
frontend/src/App.js

- Revert App.js try-catch block as it was breaking tests
- Add `npm run test:headless` script

Revert App.js try-catch block as it was breaking tests

---

frontend/src/components/CustomerReviewPage/CustomerReviewPage.js

See commit message fcb2298.
- Resolves #157
- Resolves #158
- Resolves #160 
- Resolves #161 
- Resolves #162

Small fix for CustomerReviewPage

---

frontend/e2e/cypress/integration/setPeerReview.spec.js
frontend/src/App.js
frontend/src/components/ConfigurationPage.js
frontend/src/components/LoginPage.js
frontend/src/components/RegistrationManagementPage/RegistrationManagementPage.js
frontend/src/components/RegistrationPage.js
frontend/src/components/SprintsPage/SprintsDashboard.js
frontend/src/components/TimeLogsPage/TimeLogsPage.js
frontend/src/components/ViewUsersPage/ViewUsersPage.js

Enabled the App.js `updateIsLoading(true)`. Most of the tests are working now, but there's now 2 non-working tests in `setPeerReview.spec.js`, both returning error:
> CypressError: Timed out retrying: Expected to find element: '[data-cy=menu-item-review-questions-1]', but never found it.
The `updateIsLoading(true)` in App.js causes this, not sure why. Everything seems to work when testing manually.

Fix/refactor loading handling, add isCustomerReviewPage() check to App.js

---

frontend/src/components/TimeLogsPage/TimeLogForm.js
frontend/src/components/TimeLogsPage/TimeLogsPage.js

Select current sprint by default in TimeLogsPage, Disable TimeLogForm for non-current sprints

---

frontend/src/components/TimeLogsPage/TimeLogsPage.js

Show only added sprints in time log page Sprint Selector

---

frontend/src/components/TimeLogsPage/TimeLogsPage.js

Fix form disabling logic on TimeLogsPage

---

backend/controllers/groupSprintSummary.js

resolves #240 
koko projektin kaikkien sprinttien työaika laskettu yhteen opiskilijoittain. Tulos muodossa:
[
{
"1": [
{"Joonatan Huang": 120},
{"Mikko Ahro": 150},
{"Ella Virtanen": 130},
{"Leo Niemi": 140},
{"Noora Laine": 110},
{"Sofia Heikkilä": 125},
{"Antti Korhonen": 135}
]
},
{
"2": [
{"Joonatan Huang": 90},
{"Mikko Ahro": 180},
{"Ella Virtanen": 120},
{"Leo Niemi": 160},
{"Noora Laine": 105},
{"Sofia Heikkilä": 135},
{"Antti Korhonen": 140}
]
},
{
"3": [
{"Joonatan Huang": 200},
{"Mikko Ahro": 160},
{"Ella Virtanen": 150},
{"Leo Niemi": 170},
{"Noora Laine": 120},
{"Sofia Heikkilä": 130},
{"Antti Korhonen": 125}
]
},
"Total": [
{"Joonatan Huang": 410},
{"Mikko Ahro": 490},
{"Ella Virtanen": 400},
{"Leo Niemi": 470},
{"Noora Laine": 335},
{"Sofia Heikkilä": 390},
{"Antti …

add total of all sprints to groupSprintSummary

---

backend/controllers/sprints.js
frontend/e2e/cypress/integration/timeLogs.spec.js
frontend/src/components/SprintsPage/SprintsDashboard.js
frontend/src/components/common/Notification.js

resolves 
#241 
#208
#207 
#206 
#204

prevent deleting sprints with existing time logs

---

backend/controllers/sprints.js
backend/controllers/timeLogs.js
frontend/src/components/TimeLogsPage/TimeLogsPage.js

- Order log entries by date field
- Show latest sprint by default (i.e. fixes #198)

Miscellaneous fixes for time logs

---

frontend/e2e/cypress/integration/menuItems.spec.js
frontend/src/components/common/MenuItemLists.js
frontend/src/components/common/NavigationBar.js
frontend/src/components/common/NavigationMenu.js

resolves #86 #243
menu order as per customer request 243. E2E tests added for menu items.

Fix menu order by role

---

backend/controllers/configurations.js
backend/models/configuration.js
backend/models/review_question_set.js
frontend/e2e/cypress/integration/registrationQuestionsPage.spec.js
frontend/e2e/cypress/integration/reviewQuestionsPage.spec.js

- Fix issues causing updating of configurations not to work (the rows in database weren't updated)
- Enabled some of the old non-passing tests as they pass now 🥳 
- Sorry for the Prettify

Fix issues causing updating of configurations not to work

---

backend/controllers/peerReview.js
frontend/e2e/cypress/integration/instructorPage.spec.js
frontend/e2e/cypress/integration/setPeerReview.spec.js
frontend/src/components/InstructorPage/InstructorPage.jsx
frontend/src/components/InstructorPage/StudentViewGroupAnswers.jsx
frontend/src/components/PeerReviewPage.css
frontend/src/components/PeerReviewPage.jsx
frontend/src/components/QuestionSetForm.jsx
frontend/src/reducers/actions/peerReviewPageActions.js
frontend/src/reducers/peerReviewReducer.js

resolves #192 
- Separate inputs for each team member in peer review
- Render separate peer reviews for each team member in instructor page

Separate inputs for each team member in peer review

---

frontend/package-lock.json
frontend/package.json

This PR fixes issue with react-markdown. Clicking Topic details button causes empty page because react-markdown makes the app to crash.
The issue is fixed by updating react-markdown to version 8.0.7.

Fix issue with react-markdown

---

frontend/src/components/SprintsPage/SprintsDashboard.jsx

resolves #273 #252
Date format fixed to DD/MM/YYYY (consistent with form calendar selector). Sprints sorted in dashboard according to spring number (descending)

fix SprintsDashboard sprint sorting and date format

---

frontend/e2e/cypress/common.js
frontend/e2e/cypress/integration/groupAssignmentIndicator.spec.js
frontend/src/App.jsx
frontend/src/components/RegistrationDetailsPage.jsx
frontend/src/components/SprintsPage/SprintsDashboard.jsx
frontend/src/components/TimeLogsPage/TimeLogsPage.jsx

enhanced application: group of a user participating to a project will be loaded from API on login sequence when entered to the page regardless on what subpage they are on

enhanced application: group loading

---

backend/seeders/20240319143908-add-review-question-set.js

Re-seed the local db to get the changes:
`docker-compose down --volumes`
`docker-compose up`

Update test seeders with new peerReview format

---

backend/seeders/20240319143908-add-review-question-set.js
frontend/src/components/InstructorPage/StudentViewGroupAnswers.jsx
frontend/src/components/PeerReviewPage.jsx
frontend/src/components/RegistrationDetailsPage.jsx
frontend/src/utils/functions.js

resolves #193
- In instructor page, when clicking `VIEW ANSWERS BY STUDENTS`, user should see peer reviews given to them by other people. Did this.
- Also, updated test seeders.
🚧  Will do styles in another PR!

Fix: peer reviews show incorrectly in instructor page

---

frontend/e2e/cypress/integration/instructorPage.spec.js
frontend/src/components/InstructorPage/InstructorPage.css
frontend/src/components/InstructorPage/InstructorPage.jsx
frontend/src/components/InstructorPage/StudentViewGroupAnswers.jsx

Updated instructor page styles.

Update instructor page styles

---

backend/config/sequelize.js

This PR makes it possible to run seeders in staging again.

Fix seeder config for staging

---

backend/seeders/20240429111400-add-round-2-peer-reviews.js
frontend/src/components/InstructorPage/StudentViewGroupAnswers.jsx

- Added seeders. 
- Removed `extractCallingName` from `StudentViewGroupAnswers` (this could remove the bug where Antti's review is not visible? Anyway, it's not needed there).

Add seeders for peer review round 2

---

README.md
backend/middleware.js

This PR makes it a bit easier to change roles between student, instructor and admin in dev environment.
In this PR all different user roles is added to fakeshibbo and the role is selected by modifying line `const test_user = test_users.student`, so changing one word is enough (student, instructor, admin).

Simplify changing roles between student, instructor and admin in dev environment

---

frontend/src/components/TimeLogsPage/TimeLogChart.jsx

added chart data sorting capability so that the order of bars/names are the same

added chart data sorting capability

---

backend/controllers/groups.js

This is to display time logs from all groups to instructors in addition to admin.

Fetch all groups for both instructors and admin

---

backend/controllers/instructorTimeLogs.js

Temporarily fetch all time logs for instructors.

Fetch all time logs for instructors

---

backend/controllers/timeLogs.js

There is issue that students can't add timelogs to sprint zero. This PR fixes the bug with sprint number validation.

Fix bug with sprint number validation

---

frontend/src/components/TimeLogsPage/InstructorTimeLogsPage.jsx

This PR introduces a feature that filters time logs by sprint for instructors' time logs -page.

feature: filter time logs per sprint for instructor

---

frontend/src/components/InstructorReviewPage.jsx

feature: ohjaajan arviointisivun alakohdat klikkaamalla piilotettaviksi/näytettäviksi

---

backend/controllers/instructorTimeLogs.js
frontend/src/components/TimeLogsPage/InstructorTimeLogsPage.jsx
frontend/src/components/TimeLogsPage/TimeLogRow.jsx
frontend/src/components/TimeLogsPage/TimeLogsPage.jsx
frontend/src/index.css
frontend/src/services/instructorTimeLogs.js

feature: time logien siirtäminen sprinttien välillä

---

backend/controllers/instructorTimeLogs.js
frontend/src/components/TimeLogsPage/InstructorTimeLogsPage.jsx
frontend/src/services/instructorTimeLogs.js

Fix: ohjaaja ei pysty poistamaan time logeja

---

backend/controllers/sprints.js
backend/package-lock.json

feature: Ryhmän sprinttejä pystyy hakemaan group_id:llä

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/TimeLogsPage/InstructorTimeLogsPage.jsx
frontend/src/services/sprints.js

Displays start and end date on Instructor timelogs page.

Display sprint start end date
