Ohtuilmo/ohtuilmo

backend/migrations/20190118105525-base.js, backend/migrations/20190125184855-registration_managements.js, backend/migrations/20190131082251-new-group-management.js, backend/migrations/20190221115330-peer_review.js, backend/migrations/20190228121538-fix-peer-reviews.js, backend/migrations/20190411105222-customer-review-tables.js, backend/migrations/20190418142830-instructor_review.js, backend/seeders/20190221035516-page-access-seeds.js, backend/seeders/20190226153149-group-management-seeds.js, backend/seeders/20190424111842-topic-for-active-tests.js, frontend/package.json
Issue: #6 
Changed database migration column names to snake_case. The local environment works now, but there might be more columns that require renaming.
Remember to enter `npm run db:recreate` to run the migrations.
_NOTE: the correct Node version is still a mystery but Node v12 seems to be working._
- Run `npm install` in `backend` and `frontend` directories.
- Add .env file to `backend` directory with the following content:
```
PORT = 3001
SECRET = "topsecret"
DATABASE_URI = "localhost"
EMAIL_ENABLED = "false"
```
Start a Docker container for the db:
- Enter `docker-compose up -d db` in root directory.
Create the db:
- Enter `npm run db:create` in backend directory.
- Enter `npm run db:migrate` in backend directory.
- Enter `npm run db:seed:all` in backend directory.
Start the backend: …
=> Change database migration column names to snake_case

backend/controllers/login.js, backend/index.js, backend/middleware.js
resolves: #33
- Use mock headers for dev environment.
- Changed the mock header user to Angela Merkel as she's an admin.
- Removed the isDevelopmentEnvironment() check from `/login` api as it's not needed anymore.
=> Use mock headers for dev environment

frontend/src/components/TopicListPage.js
Due to PR #74 `reverse()` is not needed anymore for rendering the latest content as default.
=> Fix: wrong content rendered as default in Topics page

frontend/src/App.js
resolves #103 
Use the old logic:
- On first render `loginUser()` is triggered, which calls `loginService.login()` and `userService.checkInstructor()`.
- After that, every 60 seconds `loginService.login()` is called.
Now the pages don't rerender every 60 sec.
=> Fix App.js loginInterval

frontend/e2e/cypress/integration/answerPeerReview.spec.js, frontend/e2e/cypress/integration/instructorReview.spec.js, frontend/e2e/cypress/integration/pageAccess.spec.js, frontend/e2e/cypress/integration/registrationQuestionsPage.spec.js, frontend/e2e/cypress/integration/reviewQuestionsPage.spec.js
- all originally failing tests (as of 24th Jan before our code changes) marked as skip
- tests are skipped one-by-one, no block skips (skip not in describe, but in "it")
- failing tests with this setup should mean that we have broken tests / code after 24th Jan
=> skip originally failing tests

frontend/e2e/cypress/integration/groupManagementPage.spec.js, frontend/e2e/cypress/integration/instructorPage.spec.js
resolves #163
Original test assumed (original) default order in configuration menu. After we changed menu order, test broke. Test fixed to explicitly choose configuration. Not feature problem, only test spec problem. Test fixed. 
In same commit (Viewing a group) deletes a student marked as skip. This works randomly, but not broken by us, but was broken before 24 Jan. This refers to issue #155 Rikkinäinen testi: (Viewing a group) deletes a student
=> fix instructorPage.spec test

backend/index.js, frontend/.eslintrc.js, frontend/e2e/cypress/integration/pageAccess.spec.js, frontend/src/App.js
- Add `e2e` directory to eslint ignorePatterns as eslint keeps nagging about Cypress functions.
- Add try-catch blocks to App.js. The login requests fail in test environment (as expected) and the errors were not caught, which caused some of the App.js fetch functions not to run and the `renders-peerreview-when-visited` test to fail.
=> Fix `renders-peerreview-when-visited` test

backend/.nvmrc, frontend/.nvmrc
From the README for [Node Version Manager](https://github.com/nvm-sh/nvm):
>You can create a `.nvmrc` file containing a node version number (or any other string that `nvm` understands; see `nvm --help` for details) in the project root directory (or any parent directory). Afterwards, `nvm use`, `nvm install`, `nvm exec`, `nvm run`, and `nvm which` will use the version specified in the `.nvmrc` file if no version is supplied on the command line.
If you'd like to, e.g., automatically use the version defined in .nvmrc when _cd_'ing, have a look at [_Deeper Shell Integration_](https://github.com/nvm-sh/nvm/#deeper-shell-integration).
The codenames of LTS versions defined in this PR correspond to
```console
$ nvm list
...
lts/dubnium -> v10.24.1
lts/erbium -> v12.22.12
...
```
=> Add .nvmrc files under backend and frontend

.github/workflows/staging.yaml
This PR fix the issue with Cypress tests in main branch. Repository secrets have to be passed explicitly to test action, otherwise test action can't read them.
=> Fix GitHub Actions issue with Cypress Record Key

backend/controllers/sprints.js, backend/controllers/timeLogs.js, backend/package-lock.json
resolves #116 
bug in spring deletion fixed. Last sprint could not be deleted, this was because empty sprint list was raising error, but it should not: no sprints is not an error, but just means that there are no sprints yet.
=> fix bug in spring deletion

backend/controllers/sprints.js
Add some more validation for sprints:
- sprint number must be the successor of the latest sprint
- sprint must start after the latest sprint has ended
Also, a bit of refactoring/cleaning up on error handling:
- no throwing errors in catch blocks
- throwing errors instead of checking a return value
- try to pass on error messages
=> More sprint validation for backend

frontend/src/components/TimeLogsPage/TimeLogsPage.js
- Fix: clicking previous sprint in Time Logs page selects the first sprint instead of the previous one
=> Fix: clicking previous sprint selects the first sprint 

.github/workflows/production.yaml
This PR adds new GitHub Actions workflow for production deployment.
- It triggers when there is a new release made in github
- The images get tag 'production'
=> Add workflow for production deployment

frontend/src/components/common/NavigationBar.css, frontend/src/components/common/NavigationBar.js
resolves #223 
- Added `user && user.user` check to `let username` to fix the typeError when logging in:
```
Uncaught TypeError: Cannot read properties of null (reading 'user')
```
- Added styles to hide the group name from navigation bar on smaller screens as it was breaking the navigation bar when it didn't fit there.
=> Fix type error in NavigationBar, hide group from NavigationBar in small screens

frontend/src/components/TimeLogsPage/TimeLogsPage.css, frontend/src/components/ViewTopicPage.js
resolves #228 
- Fix issue causing topic pages to crash
- The issue was caused by the following error:
```
Unhandled Rejection (TypeError): Cannot read properties of undefined (reading 'params')
10 | class ViewTopicPage extends React.Component {
11 |   async componentDidMount() {
> 12 |     const id = this.props.match.params.id
```
- The [React Router match object](https://v5.reactrouter.com/web/api/match) was not passed to the `ViewTopicPage` as a prop which caused the issue.
- Fixed the issue by importing [withRouter](https://v5.reactrouter.com/web/api/withRouter) which provides the `match` object as a prop (not sure how this worked before 🤔 ).
- Also, removed `align-items: flex-end;` from `TimeLogsPage.css` as it caused the form inputs to move upwards when a validation error message …
=> Fix issue causing topic pages to crash

backend/controllers/login.js, backend/controllers/logout.js
resolves #221
This is an attempt to fix the log out bug.
**Here's the HTTP request when everything works and the page redirects to the Shibboleth login page:**
**Here's the HTTP request after log out, when the page doesn't work properly and the user is not redirected to the Shibboleth login page:**
-----
The screenshots seem to indicate the issue has to do with caching of the login responses. I disabled caching for login/logout API's (as far as I understand these prolly shouldn't be cached anyway).
This fix is hard to test in dev environment as we haven't implemented the Shibboleth login there. So need to still try it out in production to verify it fixes the bug.
=> Prevent caching for login and logout

.github/workflows/test.yaml, backend/package.json, frontend/package.json
This PR adds node version used to package.json. It's good practice for developing with node.
Additionally, GitHub Actions is changed to read node versions required from package.json. This will simplify node version updates.
=> Specify node version in package.json

frontend/src/utils/userMapper.js
Navigating to the `administration/users` page resulted in the following error:
```
Unhandled Rejection (TypeError): Cannot read properties of null (reading '0')
mapSemesterField
src/utils/userMapper.js:35
32 |       break
33 |     }
34 |   }
> 35 |   parts[1] = content.match(yearPattern)[0]
36 |   return `${parts[1]} ${parts[0]}`
37 | }
38 | 
```
Fixed this by using the conditional operator.
=> Fix typeError in administration/users page

backend/seeders/20240319112824-add-new-users-and-topics.js, frontend/e2e/cypress/integration/instructorPage.spec.js, frontend/src/components/InstructorPage.css, frontend/src/components/InstructorPage.jsx, frontend/src/reducers/actions/instructorPageActions.js, frontend/src/reducers/instructorPageReducer.js
Closes #191
* New reducers to keep track of all groups and the currently selected group id on the InstructorPage.
* Added another group to seeders so test instructor has a group in two different configurations. Enables manually testing edge cases when developing.
* Rename some tests on instructorpage to make them more descriptive.
* With these reducers, only display each group's answers if the group's id matches the selected groupID on the instructor page, or if the chosen group id is 0, which is selectable by the option "all groups".
* If the instructor switches configurations when a specific group is selected, the groupselector defaults to "all groups".
=> Instructor page group filter

frontend/e2e/cypress/integration/timeLogs.spec.js, frontend/src/components/TimeLogsPage/SprintSelect.jsx, frontend/src/components/TimeLogsPage/TagSelect.jsx, frontend/src/components/TimeLogsPage/TimeLogChart.jsx, frontend/src/components/TimeLogsPage/TimeLogForm.jsx, frontend/src/components/TimeLogsPage/TimeLogsPage.css, frontend/src/components/TimeLogsPage/TimeLogsPage.jsx, frontend/src/components/common/Placeholders.jsx, frontend/src/reducers/timeLogsReducer.js
resolves #251 
resolves #277 
- Also added some styles for TimeLogsPage, TimeLogChart & TagSelect.
- Removed `isMobileView()` rendering logic as all this can be handled using CSS.
- Added logic to hide SprintSelect nextSprint/previousSprint buttons if next/previous sprint doesn't exist.
=> Update TimeLogsPage styles & fix SprintSelect bugs: sprint 0 is not selectable, clicking next sprint selects sprint 10

frontend/e2e/cypress/integration/menuItems.spec.js, frontend/src/components/common/MenuItemLists.js, frontend/src/components/common/NavigationBar.jsx
resolves #269
added new user group (relevant for men options, no other functionality depend on these groups) "Student - no group". This is for students who have either not registered yet, or are registered but not assigned to group yet. This group sees in nav menu only:
- Home (with submit registration link if not already registered)
- Register (reg form or "you have already registerd" message depending on if form has been sent already)
- Registration details
Student (assigned to group) sees in menu:
- Home (redirects to registration details)
- Registration details
- Peer review
- Time Logs
- Sprint Dashboard
Instructor sees instructor items + Student items + Student-no group items
Admin see admin items + Instructor + Student + Student - no group items
Navigation menu tests updated & new …
=> add new user group 'student - no group' and change nav bar

frontend/src/components/TimeLogsPage/TimeLogRow.jsx
This PR prevents users from deleting time logs, until we have fixed the bug where all time logs are displayed to all users.
=> hotfix: remove log delete btn until log display fixed

backend/controllers/timeLogs.js
Something seems to be wrong with the instructor checking, so this commit prevents anyone but admin from fetching all time logs.
This PR will prevent users (and instructors) from seeing timelogs by other users.
=> fix: all timelogs being visible to all students

frontend/src/components/TimeLogsPage/InstructorTimeLogsPage.jsx
This PR introduces a feature that automatically selects the latest configuration and group for instructors when viewing time logs for their group of students.
Made in collaboration between @amandahamynen and @VSirvio
=> feature: instructor time logs automatically select correct configuration and group

frontend/src/components/TimeLogsPage/TimeLogsSelectForm.jsx
This PR fixes the bug found in issue #312 by increasing the z-index for dropdown menus. The menus now appear over the header bar.
Made in collaboration between @amandahamynen  and @VSirvio. 
Closes #312
=> fix: pudotusvalikkojen ylimpiä vaihtoehtoja ei ohjaajan time log -sivulla pysty aina valitsemaan
